apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: floor-control
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/local/floor-control/postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: floor-control
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: floor-control
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-data
