apiVersion: v1
kind: Service
metadata:
  name: floor-control-api
  namespace: floor-control
  labels:
    app.kubernetes.io/name: floor-control-api
    app.kubernetes.io/part-of: floor-control
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: floor-control-api
  ports:
    - name: http
      port: 4000
      targetPort: http
      nodePort: 30080
